<?php
    $f3 = Base::instance();
    session_start();
    $db_name = $_SESSION['db_name'];
    $db_nickname = $_SESSION['db_nickname'];
    $db_pass = $_SESSION['db_pass'];
    $db_host = $_SESSION['db_host'];
    $admin_nickname = $_SESSION['admin_nickname'];
    $admin_email = $_SESSION['admin_email'];
    $smtp_email = $_SESSION['smtp_email'];
    $smtp_pass = $_SESSION['smtp_pass'];
    $smtp_port = $_SESSION['smtp_port'];
    $smtp_host = $_SESSION['smtp_host'];
    $smtp_method = $_SESSION['smtp_method'];
    $vtc_name = $_SESSION['vtc_name'];
    $vtc_logo = $_SESSION['vtc_logo'];
    $vtc_slogan = $_SESSION['vtc_slogan'];
    $vtc_tmpid = $_SESSION['vtc_tmpid'];
    $api_key = $_SESSION['api_key'];
    $f3->set('db',new DB\SQL(
        'mysql:host='.$db_host.';post=3306;dbname='.$db_name,
        $db_nickname,
        $db_pass
    ));
    $db = $f3->get('db');
    if($db)
    {
        //Begin function - importing SQL stuff
        $f3->set('result1',$db->exec('CREATE TABLE `cities` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `name` varchar(50) NOT NULL,
            `short_name` varchar(50) NOT NULL,
            `game` tinyint(1) NOT NULL,
            `id_dlc` int(11) NOT NULL,
            PRIMARY KEY(`id`)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'));
        $f3->set('result1',$db->exec('INSERT INTO `cities` (`id`, `name`, `short_name`, `game`, `id_dlc`) VALUES
            (1, "Lublin", "lublin", 0, 1),
            (2, "Stavanger", "stavanger", 0, 2),
            (3, "Wrocław", "wrocław", 0, 0),
            (4, "Erfurt", "erfurt", 0, 0),
            (5, "Metz", "metz", 0, 0),
            (6, "Paris", "paris", 0, 0),
            (7, "Liverpool", "liverpool", 0, 0),
            (8, "Graz", "graz", 0, 0),
            (9, "Luxembourg", "luxembourg", 0, 0),
            (10, "Poznań", "poznań", 0, 0),
            (11, "Budapest", "budapest", 0, 1),
            (12, "Dortmund", "dortmund", 0, 0),
            (13, "Rotterdam", "rotterdam", 0, 0),
            (14, "Bratislava", "bratislava", 0, 0),
            (15, "Berlin", "berlin", 0, 0),
            (16, "Southampton", "southampton", 0, 0),
            (17, "Debrecen", "debrecen", 0, 1),
            (18, "Hannover", "hannover", 0, 0),
            (19, "Kiel", "kiel", 0, 0),
            (20, "Rostock", "rostock", 0, 0),
            (21, "Dresden", "dresden", 0, 0),
            (22, "London", "london", 0, 0),
            (23, "Brno", "brno", 0, 0),
            (24, "Birmingham", "birmingham", 0, 0),
            (25, "Aberdeen", "aberdeen", 0, 0),
            (26, "Salzburg", "salzburg", 0, 0),
            (27, "Lyon", "lyon", 0, 0),
            (28, "Sheffield", "sheffield", 0, 0),
            (29, "Edinburgh", "edinburgh", 0, 0),
            (30, "Stockholm", "stockholm", 0, 2),
            (31, "Katowice", "katowice", 0, 1),
            (32, "Karlskrona", "karlskrona", 0, 2),
            (33, "Manchester", "manchester", 0, 0),
            (34, "Cardiff", "cardiff", 0, 0),
            (35, "Odense", "odense", 0, 2),
            (36, "Kristiansand", "kristiansand", 0, 2),
            (37, "Hamburg", "hamburg", 0, 0),
            (38, "Bremen", "bremen", 0, 0),
            (39, "Felixstowe", "felixstowe", 0, 0),
            (40, "Calais", "calais", 0, 0),
            (41, "Swansea", "swansea", 0, 0),
            (42, "Plymouth", "plymouth", 0, 0),
            (43, "Carlisle", "carlisle", 0, 0),
            (44, "Łódź", "łódź", 0, 1),
            (45, "Brussel", "brussel", 0, 0),
            (46, "Uppsala", "uppsala", 0, 2),
            (47, "Szczecin", "szczecin", 0, 0),
            (48, "Szeged", "szeged", 0, 1),
            (49, "Gdańsk", "gdańsk", 0, 1),
            (50, "Milano", "milano", 0, 0),
            (51, "Dijon", "dijon", 0, 0),
            (52, "Warszawa", "warszawa", 0, 1),
            (53, "Stuttgart", "stuttgart", 0, 0),
            (54, "Bern", "bern", 0, 0),
            (55, "Kraków", "kraków", 0, 1),
            (56, "Bergen", "bergen", 0, 2),
            (57, "Linz", "linz", 0, 0),
            (58, "Praha", "praha", 0, 0),
            (59, "Amsterdam", "amsterdam", 0, 0),
            (60, "Esbjerg", "esbjerg", 0, 2),
            (61, "Helsingborg", "helsingborg", 0, 2),
            (62, "Aalborg", "aalborg", 0, 2),
            (63, "Oslo", "oslo", 0, 2),
            (64, "Ostrava", "ostrava", 0, 1),
            (65, "Groningen", "groningen", 0, 0),
            (66, "Wien", "wien", 0, 0),
            (67, "Hirtshals", "hirtshals", 0, 2),
            (68, "Torino", "torino", 0, 0),
            (69, "Białystok", "białystok", 0, 1),
            (70, "Mannheim", "mannheim", 0, 0),
            (71, "Olsztyn", "olsztyn", 0, 1),
            (72, "Venezia", "venezia", 0, 0),
            (73, "Klagenfurt am Worthersee", "klagenfurt am worthersee", 0, 0),
            (74, "Cambridge", "cambridge", 0, 0),
            (75, "Grimsby", "grimsby", 0, 0),
            (76, "Dover", "dover", 0, 0),
            (77, "Kalmar", "kalmar", 0, 2),
            (78, "Strasbourg", "strasbourg", 0, 0),
            (79, "Glasgow", "glasgow", 0, 0),
            (80, "Jackpot", "jackpot", 1, 0),
            (81, "Los Angeles", "los angeles", 1, 0),
            (82, "Elko", "elko", 1, 0),
            (83, "San Diego", "san diego", 1, 0),
            (84, "Winnemucca", "winnemucca", 1, 0),
            (85, "Truckee", "truckee", 1, 0),
            (86, "Reno", "reno", 1, 0),
            (87, "Santa Cruz", "santa cruz", 1, 0),
            (88, "Primm", "primm", 1, 0),
            (89, "Las Vegas", "las vegas", 1, 0),
            (90, "San Francisco", "san francisco", 1, 0),
            (91, "Bakersfield", "bakersfield", 1, 0),
            (92, "Tonopah", "tonopah", 1, 0),
            (93, "Oxnard", "oxnard", 1, 0),
            (94, "Stockton", "stockton", 1, 0),
            (95, "Eureka", "eureka", 1, 0),
            (96, "Ely", "ely", 1, 0),
            (97, "Oakland", "oakland", 1, 0),
            (98, "Sacramento", "sacramento", 1, 0),
            (99, "Fresno", "fresno", 1, 0),
            (100, "Redding", "redding", 1, 0),
            (101, "Carlsbad", "carlsbad", 1, 7),
            (102, "Barstow", "barstow", 1, 0),
            (103, "Huron", "huron", 1, 0),
            (104, "Verona", "verona", 0, 0),
            (105, "Carson City", "carson city", 1, 0),
            (106, "San Rafael", "san rafael", 1, 0),
            (107, "Oakdale", "oakdale", 1, 0),
            (108, "Pioche", "pioche", 1, 0),
            (109, "El Centro", "el centro", 1, 0),
            (110, "Trelleborg", "trelleborg", 0, 2),
            (111, "Hornbrook", "hornbrook", 1, 0),
            (112, "Kassel", "kassel", 0, 0),
            (113, "Duisburg", "duisburg", 0, 0),
            (114, "Reims", "reims", 0, 0),
            (115, "Lille", "lille", 0, 0),
            (116, "Innsbruck", "innsbruck", 0, 0),
            (117, "Leipzig", "leipzig", 0, 0),
            (118, "Magdeburg", "magdeburg", 0, 0),
            (119, "Frederikshavn", "frederikshavn", 0, 2),
            (120, "Gedser", "gedser", 0, 2),
            (121, "Frankfurt am Main", "frankfurt am main", 0, 0),
            (122, "Newcastle-upon-Tyne", "newcastle-upon-tyne", 0, 0),
            (123, "Linkoping", "linkoping", 0, 2),
            (124, "Geneve", "geneve", 0, 0),
            (125, "Koln", "koln", 0, 0),
            (126, "Kayenta", "kayenta", 1, 0),
            (127, "Nogales", "nogales", 1, 0),
            (128, "Tucson", "tucson", 1, 0),
            (129, "Flagstaff", "flagstaff", 1, 0),
            (130, "Camp Verde", "camp verde", 1, 0),
            (131, "Page", "page", 1, 0),
            (132, "Phoenix", "phoenix", 1, 0),
            (133, "Holbrook", "holbrook", 1, 0),
            (134, "Yuma", "yuma", 1, 0),
            (135, "Grand Canyon Village", "grand canyon village", 1, 0),
            (136, "Kingman", "kingman", 1, 0),
            (137, "Ukiah", "ukiah", 1, 0),
            (138, "Sierra Vista", "sierra vista", 1, 0),
            (139, "San Simon", "san simon", 1, 0),
            (140, "Ehrenberg", "ehrenberg", 1, 0),
            (141, "Show Low", "show low", 1, 0),
            (142, "Vaxjo", "vaxjo", 0, 2),
            (143, "Banska Bystrica", "banska bystrica", 0, 1),
            (144, "Liege", "liege", 0, 0),
            (145, "Zurich", "zurich", 0, 0),
            (146, "Malmo", "malmo", 0, 2),
            (147, "Dusseldorf", "dusseldorf", 0, 0),
            (148, "Goteborg", "goteborg", 0, 2),
            (149, "Jonkoping", "jonkoping", 0, 2),
            (150, "Kosice", "kosice", 0, 1),
            (151, "Munchen", "munchen", 0, 0),
            (152, "Nurnberg", "nurnberg", 0, 0),
            (153, "Pecs", "pecs", 0, 1),
            (154, "Orebro", "orebro", 0, 2),
            (155, "Vasteras", "vasteras", 0, 2),
            (156, "Osnabruck", "osnabruck", 0, 0),
            (157, "Sodertalje", "sodertalje", 0, 2),
            (158, "Kobenhavn", "kobenhavn", 0, 2),
            (159, "Bordeaux", "bordeaux", 0, 3),
            (160, "Bourges", "bourges", 0, 3),
            (161, "Brest", "brest", 0, 3),
            (162, "Civaux", "civaux", 0, 3),
            (163, "Clermont-Ferrand", "clermont-ferrand", 0, 3),
            (164, "Golfech", "golfech", 0, 3),
            (165, "La Rochelle", "la rochelle", 0, 3),
            (166, "Le Havre", "le havre", 0, 3),
            (167, "Limoges", "limoges", 0, 3),
            (168, "Marseille", "marseille", 0, 3),
            (169, "Montpellier", "montpellier", 0, 3),
            (170, "Nantes", "nantes", 0, 3),
            (171, "Nice", "nice", 0, 3),
            (172, "Paluel", "paluel", 0, 3),
            (173, "Rennes", "rennes", 0, 3),
            (174, "Roscoff", "roscoff", 0, 3),
            (175, "Saint-Laurent", "saint-laurent", 0, 3),
            (176, "Toulouse", "toulouse", 0, 3),
            (177, "Saint-Alban-du-Rhone", "saint-alban-du-rhone", 0, 3),
            (178, "Le Mans", "le mans", 0, 3),
            (179, "Santa Maria", "santa maria", 1, 0),
            (180, "Andorra la Vella", "andorra la vella", 0, 0),
            (181, "Antwerpen", "antwerpen", 0, 0),
            (182, "Ruse", "ruse", 0, 0),
            (183, "Aarhus", "aarhus", 0, 0),
            (184, "Herning", "herning", 0, 0),
            (185, "Holstebro", "holstebro", 0, 0),
            (186, "Kolding", "kolding", 0, 0),
            (187, "Padborg", "padborg", 0, 0),
            (188, "Rodbyhavn", "rodbyhavn", 0, 0),
            (189, "Viborg", "viborg", 0, 0),
            (190, "Haapsalu", "haapsalu", 0, 0),
            (191, "Kardla", "kardla", 0, 0),
            (192, "Kuressaare", "kuressaare", 0, 0),
            (193, "Narva", "narva", 0, 5),
            (194, "Pärnu", "pärnu", 0, 5),
            (195, "Rakvere", "rakvere", 0, 0),
            (196, "Tallinn", "tallinn", 0, 5),
            (197, "Tartu", "tartu", 0, 5),
            (198, "Valga", "valga", 0, 0),
            (199, "Klaksvik", "klaksvik", 0, 0),
            (200, "Torshavn", "torshavn", 0, 0),
            (201, "Alajarvi", "alajarvi", 0, 0),
            (202, "Hämeenlinna", "hämeenlinna", 0, 0),
            (203, "Helsinki", "helsinki", 0, 5),
            (204, "Joensuu", "joensuu", 0, 0),
            (205, "Jyväskylä", "jyväskylä", 0, 0),
            (206, "Karsamaki", "karsamaki", 0, 0),
            (207, "Kemi", "kemi", 0, 0),
            (208, "Kemijärvi", "kemijärvi", 0, 0),
            (209, "Kristiinankaupunki", "kristiinankaupunki", 0, 0),
            (210, "Kuopio", "kuopio", 0, 0),
            (211, "Lahti", "lahti", 0, 5),
            (212, "Mikkeli", "mikkeli", 0, 0),
            (213, "Napapiiri", "napapiiri", 0, 0),
            (214, "Oulu", "oulu", 0, 0),
            (215, "Pori", "pori", 0, 5),
            (216, "Porvoo", "porvoo", 0, 0),
            (217, "Rovaniemi", "rovaniemi", 0, 0),
            (218, "Varkaus", "varkaus", 0, 0),
            (219, "Vaasa", "vaasa", 0, 0),
            (220, "Tampere", "tampere", 0, 5),
            (221, "Tornio", "tornio", 0, 0),
            (222, "Turku", "turku", 0, 5),
            (223, "Vantaa", "vantaa", 0, 0),
            (224, "Viitasaari", "viitasaari", 0, 0),
            (225, "Angers", "angers", 0, 0),
            (226, "Bayonne", "bayonne", 0, 0),
            (227, "Caen", "caen", 0, 0),
            (228, "Cherbourg", "cherbourg", 0, 0),
            (229, "Lorient", "lorient", 0, 0),
            (230, "Narbonne", "narbonne", 0, 0),
            (231, "Orléans", "orléans", 0, 0),
            (232, "Rouen", "rouen", 0, 0),
            (233, "Pau", "pau", 0, 0),
            (234, "Perpignan", "perpignan", 0, 0),
            (235, "Poitiers", "poitiers", 0, 0),
            (236, "Tours", "tours", 0, 0),
            (237, "Aurach", "aurach", 0, 0),
            (238, "Bad Oeynhausen", "bad oeynhausen", 0, 0),
            (239, "Bremerhaven", "bremerhaven", 0, 0),
            (240, "Burg A. Fehmarn", "burg a. fehmarn", 0, 0),
            (241, "Halle", "halle", 0, 0),
            (242, "Heilbronn", "heilbronn", 0, 0),
            (243, "Flensburg", "flensburg", 0, 0),
            (244, "Furth", "furth", 0, 0),
            (245, "Oberhausen", "oberhausen", 0, 0),
            (246, "Ulm", "ulm", 0, 0),
            (247, "Akranes", "akranes", 0, 0),
            (248, "Akureyri", "akureyri", 0, 0),
            (249, "Blonduos", "blonduos", 0, 0),
            (250, "Bolungarvik", "bolungarvik", 0, 0),
            (251, "Borgarnes", "borgarnes", 0, 0),
            (252, "Hofn", "hofn", 0, 0),
            (253, "Holmavik", "holmavik", 0, 0),
            (254, "Isafjordur", "isafjordur", 0, 0),
            (255, "Keflavik International Airport", "keflavik international airport", 0, 0),
            (256, "Krafla", "krafla", 0, 0),
            (257, "Reykjavik", "reykjavik", 0, 0),
            (258, "Reyðarfjörður", "reyðarfjörður", 0, 0),
            (259, "Selfoss", "selfoss", 0, 0),
            (260, "Seyðisfjörður", "seyðisfjörður", 0, 0),
            (261, "Vik", "vik", 0, 0),
            (262, "Douglas", "douglas", 0, 0),
            (263, "Ramsey", "ramsey", 0, 0),
            (264, "Bologna", "bologna", 0, 4),
            (265, "Firenze", "firenze", 0, 4),
            (266, "Genova", "genova", 0, 4),
            (267, "Livorno", "livorno", 0, 4),
            (268, "Modena", "modena", 0, 0),
            (269, "Parma", "parma", 0, 4),
            (270, "Vicenza", "vicenza", 0, 0),
            (271, "Saint Helier", "saint helier", 0, 0),
            (272, "Trinity", "trinity", 0, 0),
            (273, "Balvi", "balvi", 0, 0),
            (274, "Gulbene", "gulbene", 0, 0),
            (275, "Jekabpils", "jekabpils", 0, 0),
            (276, "Kolka", "kolka", 0, 0),
            (277, "Liepaja", "liepaja", 0, 5),
            (278, "Ogre", "ogre", 0, 0),
            (279, "Valka", "valka", 0, 0),
            (280, "Ventspils", "ventspils", 0, 5),
            (281, "Riga", "riga", 0, 5),
            (282, "Rezekne", "rezekne", 0, 5),
            (283, "Saldus", "saldus", 0, 0),
            (284, "Tukums", "tukums", 0, 0),
            (285, "Vaduz", "vaduz", 0, 0),
            (286, "Kaunas", "kaunas", 0, 5),
            (287, "Klaipeda", "klaipeda", 0, 5),
            (288, "Panevezys", "panevezys", 0, 5),
            (289, "Balti", "balti", 0, 0),
            (290, "Chisinau", "chisinau", 0, 0),
            (291, "Arnhem", "arnhem", 0, 0),
            (292, "Eindhoven", "eindhoven", 0, 0),
            (293, "Europoort", "europoort", 0, 0),
            (294, "IJmuiden", "ijmuiden", 0, 0),
            (295, "Zwolle", "zwolle", 0, 0),
            (296, "Kirkenes", "kirkenes", 0, 0),
            (297, "Longyearbyen", "longyearbyen", 0, 0),
            (298, "Moskushamn", "moskushamn", 0, 0),
            (299, "Bielsko-Biała", "bielsko-biała", 0, 0),
            (300, "Bydgoszcz", "bydgoszcz", 0, 0),
            (301, "Cieszyn", "cieszyn", 0, 0),
            (302, "Gdynia", "gdynia", 0, 0),
            (303, "Gorzów Wielkopolski", "gorzów wielkopolski", 0, 0),
            (304, "Gorzów Wielkopolski", "gorzów wielkopolski", 0, 0),
            (305, "Grudziądz", "grudziądz", 0, 0),
            (306, "Kielce", "kielce", 0, 0),
            (307, "Koszalin", "koszalin", 0, 0),
            (308, "Krosno", "krosno", 0, 0),
            (309, "Nowogard", "nowogard", 0, 0),
            (310, "Opole", "opole", 0, 0),
            (311, "Ostrołęka", "ostrołęka", 0, 0),
            (312, "Piła", "piła", 0, 0),
            (313, "Płock", "płock", 0, 0),
            (314, "Przemyśl", "przemyśl", 0, 0),
            (315, "Radom", "radom", 0, 0),
            (316, "Rzeszów", "rzeszów", 0, 0),
            (317, "Sanok", "sanok", 0, 0),
            (318, "Siedlce", "siedlce", 0, 0),
            (319, "Suwałki", "suwałki", 0, 0),
            (320, "Świnoujście", "świnoujście", 0, 0),
            (321, "Zamość", "zamość", 0, 0),
            (322, "Zgorzelec", "zgorzelec", 0, 0),
            (323, "Arad", "arad", 0, 0),
            (324, "Baia Mare", "baia mare", 0, 0),
            (325, "Cluj-Napoca", "cluj-napoca", 0, 0),
            (326, "Oradea", "oradea", 0, 0),
            (327, "Timisoara", "timisoara", 0, 0),
            (328, "Sibiu", "sibiu", 0, 0),
            (329, "Bacau", "bacau", 0, 0),
            (330, "Piatra-Neamt", "piatra-neamt", 0, 0),
            (331, "Bucharest", "bucharest", 0, 0),
            (332, "Constanta", "constanta", 0, 0),
            (333, "Craiova", "craiova", 0, 0),
            (334, "Satu Mare", "satu mare", 0, 0),
            (335, "Murmansk", "murmansk", 0, 0),
            (336, "Nikel", "nikel", 0, 0),
            (337, "Zelenogradsk", "zelenogradsk", 0, 0),
            (338, "Ljubljana", "ljubljana", 0, 0),
            (339, "Maribor", "maribor", 0, 0),
            (340, "Celje", "celje", 0, 0),
            (341, "Novo Mesto", "novo mesto", 0, 0),
            (342, "Kranj", "kranj", 0, 0),
            (343, "Koper", "koper", 0, 0),
            (344, "Nova Gorica", "nova gorica", 0, 0),
            (345, "Bled", "bled", 0, 0),
            (346, "Kamnik", "kamnik", 0, 0),
            (347, "Barcelona", "barcelona", 0, 0),
            (348, "Bilbao", "bilbao", 0, 0),
            (349, "Irun", "irun", 0, 0),
            (350, "La Jonquera", "la jonquera", 0, 0),
            (351, "Manresa", "manresa", 0, 0),
            (352, "San Sebastian", "san sebastian", 0, 0),
            (353, "Haparanda", "haparanda", 0, 0),
            (354, "Gävle", "gävle", 0, 0),
            (355, "Karlstad", "karlstad", 0, 0),
            (356, "Kristianstad", "kristianstad", 0, 0),
            (357, "Örnsköldsvik", "örnsköldsvik", 0, 0),
            (358, "Söderhamn", "söderhamn", 0, 0),
            (359, "Sundsvall", "sundsvall", 0, 0),
            (360, "Umeå", "umeå", 0, 0),
            (361, "Basel", "basel", 0, 0),
            (362, "Mukacheve", "mukacheve", 0, 0),
            (363, "Uzhhorod", "uzhhorod", 0, 0),
            (364, "Birsay", "birsay", 0, 0),
            (365, "Broadford", "broadford", 0, 0),
            (366, "Chelmsford", "chelmsford", 0, 0),
            (367, "Croydon", "croydon", 0, 0),
            (368, "Evie", "evie", 0, 0),
            (369, "Fort William", "fort william", 0, 0),
            (370, "Heysham", "heysham", 0, 0),
            (371, "Inverness", "inverness", 0, 0),
            (372, "Kirkwall", "kirkwall", 0, 0),
            (373, "Oban", "oban", 0, 0),
            (374, "Portree", "portree", 0, 0),
            (375, "Portsmouth", "portsmouth", 0, 0),
            (376, "Stromness", "stromness", 0, 0),
            (377, "Thurso", "thurso", 0, 0),
            (378, "Wick", "wick", 0, 0),
            (379, "Orsha", "orsha", 0, 0),
            (380, "Tampa", "tampa", 1, 0),
            (381, "Cabo San Lucas", "cabo san lucas", 1, 0),
            (382, "Tijuana", "tijuana", 1, 0),
            (383, "Chicago", "chicago", 1, 0),
            (384, "Little Rock", "little rock", 1, 0),
            (385, "Milwaukee", "milwaukee", 1, 0),
            (386, "Winnipeg", "winnipeg", 1, 0),
            (387, "Prince George", "prince george", 1, 0),
            (388, "Iowa 80", "iowa 80", 1, 0),
            (389, "Guaymas", "guaymas", 1, 0),
            (390, "McDermitt", "mcdermitt", 1, 0),
            (391, "Miami", "miami", 1, 0),
            (392, "Punta Abreojos", "punta abreojos", 1, 0),
            (393, "Huesca", "huesca", 0, 0),
            (394, "Nynashamn", "nynashamn", 0, 2),
            (395, "Slavonski Brod", "slavonski brod", 0, 0),
            (396, "Kokkola", "kokkola", 0, 0),
            (397, "Trondheim", "trondheim", 0, 0),
            (398, "Bonn", "bonn", 0, 0),
            (399, "Gavle", "gavle", 0, 0),
            (400, "Sodankyla", "sodankyla", 0, 0),
            (401, "Hainburg a. d. Donau", "hainburg a. d. donau", 0, 0),
            (402, "Łeba", "łeba", 0, 0),
            (403, "Lębork", "lębork", 0, 0),
            (404, "Elbląk", "elbląk", 0, 0),
            (405, "Ostróda", "ostróda", 0, 0),
            (406, "Legnica", "legnica", 0, 0),
            (407, "Wałcz", "wałcz", 0, 0),
            (408, "Kaliningrad", "kaliningrad", 0, 5),
            (409, "Limerick", "limerick", 0, 0),
            (410, "Albuquerque", "albuquerque", 1, 7),
            (411, "Alamogordo", "alamogordo", 1, 7),
            (412, "Artesia", "artesia", 1, 7),
            (413, "Clovis", "clovis", 1, 7),
            (414, "Farmington", "farmington", 1, 7),
            (415, "Gallup", "gallup", 1, 7),
            (416, "Hobbs", "hobbs", 1, 7),
            (417, "Las Cruces", "las cruces", 1, 7),
            (418, "Raton", "raton", 1, 7),
            (419, "Roswell", "roswell", 1, 7),
            (420, "Santa Fe", "santa fe", 1, 7),
            (421, "Socorro", "socorro", 1, 7),
            (422, "Tucumcari", "tucumcari", 1, 7),
            (423, "Suzzara", "suzzara", 0, 4),
            (424, "Ancona", "ancona", 0, 4),
            (425, "Terni", "terni", 0, 4),
            (426, "Roma", "roma", 0, 4),
            (427, "Pescara", "pescara", 0, 4),
            (428, "Cassino", "cassino", 0, 4),
            (429, "Napoli", "napoli", 0, 4),
            (430, "Bari", "bari", 0, 4),
            (431, "Taranto", "taranto", 0, 4),
            (432, "Catanzaro", "catanzaro", 0, 4),
            (433, "Palermo", "palermo", 0, 4),
            (434, "Catania", "catania", 0, 4),
            (435, "Messina", "messina", 0, 4),
            (436, "Villa San Giovanni", "villa san giovanni", 0, 4),
            (437, "testowe", "testowe", 0, 0),
            (438, "Daugavpils", "daugavpils", 0, 5),
            (439, "Pendleton", "pendleton", 1, 8),
            (440, "Ontario", "ontario", 1, 8),
            (441, "Burns", "burns", 1, 8),
            (442, "Lakeview", "lakeview", 1, 8),
            (443, "Klamath Falls", "klamath falls", 1, 8),
            (444, "Medford", "medford", 1, 8),
            (445, "Coos Bay", "coos bay", 1, 8),
            (446, "Eugene", "eugene", 1, 8),
            (447, "Bend", "bend", 1, 8),
            (448, "Newport", "newport", 1, 8),
            (449, "Salem", "salem", 1, 8),
            (450, "The Dalles", "the dalles", 1, 8),
            (451, "Portland", "portland", 1, 8),
            (452, "Astoria", "astoria", 1, 8),
            (453, "Naantali", "naantali", 0, 5),
            (454, "Kłajpeda", "kłajpeda", 0, 0),
            (455, "Windawa", "windawa", 0, 0),
            (456, "Kowno", "kowno", 0, 0),
            (457, "Vilnius", "vilnius", 0, 5),
            (458, "Lipawa", "lipawa", 0, 0),
            (459, "Możejki", "możejki", 0, 0),
            (460, "Szawle", "szawle", 0, 0),
            (461, "Poniewież", "poniewież", 0, 0),
            (462, "Uciana", "uciana", 0, 0),
            (463, "Ryga", "ryga", 0, 0),
            (464, "Dyneburg", "dyneburg", 0, 0),
            (465, "Rzeżyca", "rzeżyca", 0, 0),
            (466, "Valmiera", "valmiera", 0, 5),
            (467, "Pskov", "pskov", 0, 5),
            (468, "Parnawa", "parnawa", 0, 0),
            (469, "Paldiski", "paldiski", 0, 5),
            (470, "Kunda", "kunda", 0, 5),
            (471, "Luga", "Luga", 0, 5),
            (472, "Sosnowy Bor", "sosnowy bor", 0, 5),
            (473, "Sankt Petersburg", "sankt petersburg", 0, 0),
            (474, "Vyborg", "vyborg", 0, 5),
            (475, "Kotka", "kotka", 0, 5),
            (476, "Kouvola", "kouvola", 0, 5),
            (477, "Loviisa", "loviisa", 0, 5),
            (478, "Olkiluoto", "olkiluoto", 0, 5),
            (479, "Kapellskar", "kapellskar", 0, 2),
            (480, "Travemunde", "travemunde", 0, 0),
            (481, "Kolonia", "kolonia", 0, 0),
            (482, "Werona", "werona", 0, 0),
            (483, "Strasburg", "strasburg", 0, 0),
            (484, "Frankfurt nad Menem", "frankfurt nad menem", 0, 0),
            (485, "Paryż", "paryż", 0, 0),
            (486, "Florencja", "florencja", 0, 0),
            (487, "Luksemburg", "luksemburg", 0, 0),
            (488, "Bratysława", "bratysława", 0, 0),
            (489, "Kilonia", "kilonia", 0, 0),
            (490, "Widyń", "widyń", 0, 0),
            (491, "Zagrzeb", "zagrzeb", 0, 0),
            (492, "Sassari", "sassari", 0, 4),
            (493, "Olbia", "olbia", 0, 4),
            (494, "Cagliari", "cagliari", 0, 4),
            (495, "Wenecja", "wenecja", 0, 0),
            (496, "Colville", "colville", 1, 9),
            (497, "Clifton", "clifton", 1, 0),
            (498, "Monachium", "monachium", 0, 0),
            (499, "Norymberga", "norymberga", 0, 0),
            (500, "Londyn", "londyn", 0, 0),
            (501, "Mazeikiai", "mazeikiai", 0, 5),
            (502, "Saint Petersburg", "saint Petersburg", 0, 5),
            (503, "Siauliai", "siauliai", 0, 5),
            (504, "Utena", "utena", 0, 5),
            (505, "Aberdeen", "aberdeen", 1, 9),
            (506, "Bellingham", "bellingham", 1, 9),
            (507, "Everett", "everett", 1, 9),
            (508, "Grand Coulee", "grand coulee", 1, 9),
            (509, "Kennewick", "kennewick", 1, 9),
            (510, "Longview", "longview", 1, 9),
            (511, "Olympia", "olympia", 1, 9),
            (512, "Omak", "omak", 1, 9),
            (513, "Port Angeles", "port angeles", 1, 9),
            (514, "Seattle", "seattle", 1, 9),
            (515, "Spokane", "spokane", 1, 9),
            (516, "Tacoma", "tacoma", 1, 9),
            (517, "Vancouver", "vancouver", 1, 9),
            (518, "Wenatchee", "wenatchee", 1, 9),
            (519, "Yakima", "yakima", 1, 9)'    
        ));
        $result1 = $f3->get('result1');
        if($result1)
        {
            $f3->set('result2',$db->exec('CREATE TABLE `companies` (
                `id` int(11) NOT NULL AUTO_INCREMENT,
                `name` varchar(50) NOT NULL,
                `short_name` varchar(50) NOT NULL,
                `game` tinyint(1) NOT NULL,
                PRIMARY KEY(`id`)
              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'));
            $f3->set('result2',$db->exec('INSERT INTO `companies` (`id`, `name`, `short_name`, `game`) VALUES
            (1, "AA - Auto di Alonso", "aa_auto", 0),
            (2, "ACC", "acc", 0),
            (3, "ACI SRL", "aci_srl", 0),
            (4, "AeroBaltica", "aerobaltica", 0),
            (5, "Agrominta UAB", "agrominta_uab", 0),
            (6, "Agronord", "agronord", 0),
            (7, "Aria", "aria", 0),
            (8, "Ateria AS", "ateria_as", 0),
            (9, "Balteus Yachts", "balteus_yachts", 0),
            (10, "Baltic Logistic Transport", "baltic_logistic_transport", 0),
            (11, "Baltic Metallurgy", "baltic_metallurgy", 0),
            (12, "Baltomorsk", "baltomorsk", 0),
            (13, "Batisse", "batisse", 0),
            (14, "BCP", "bcp", 0),
            (15, "BHB La Raffinerie", "bhb_la_raffinerie", 0),
            (16, "BHV", "bhv", 0),
            (17, "Bjork", "bjork", 0),
            (18, "Boisserie Jean-Pierre", "boisserie_jean-pierre", 0),
            (19, "Cantiere Navale", "cantiere_navale", 0),
            (20, "Cargotras", "cargotras", 0),
            (21, "Cemeltex", "cemeltex", 0),
            (22, "Cesare Supermercato", "cesare_supermercato", 0),
            (23, "Chimi", "chimi", 0),
            (24, "CNP", "cnp", 0),
            (25, "Comoto", "comoto", 0),
            (26, "Container Port", "container_port", 0),
            (27, "Construzione di Edifici", "construzione_di_edifici", 0),
            (28, "Dans le Jardin", "dans_le_jardin", 0),
            (29, "Domdepo", "domdepo", 0),
            (30, "Drekkar Trans", "drekkar_trans", 0),
            (31, "Eco", "eco", 0),
            (32, "Eolo Lines", "eolo_lines", 0),
            (33, "Estonian Paper AS", "estonian_paper_as", 0),
            (34, "EuroAcres", "euroacres", 0),
            (35, "EuroGoodies", "eurogoodies", 0),
            (36, "Eviksi ZS", "eviksi_zs", 0),
            (37, "Exomar", "exomar", 0),
            (38, "Fattoria Felice", "fattoria_felice", 0),
            (39, "FCP", "fcp", 0),
            (40, "Finnish Tyres", "finnish_tyres", 0),
            (41, "FLE", "fle", 0),
            (42, "FUISpA", "fuispa", 0),
            (43, "Gallia Ferries", "gallia_ferries", 0),
            (44, "Gasmer", "gasmer", 0),
            (45, "Globeur", "globeur", 0),
            (46, "GNT", "gnt", 0),
            (47, "GOB", "gob", 0),
            (48, "Gomme du Monde", "gomme_du_monde", 0),
            (49, "Huilant", "huilant", 0),
            (50, "IKA Bohag", "ika_bohag", 0),
            (51, "INI", "ini", 0),
            (52, "International Baltic Petroleum", "international_baltic_petroleum", 0),
            (53, "ITCC", "itcc", 0),
            (54, "Kaarfor", "kaarfor", 0),
            (55, "Konstnorr", "konstnorr", 0),
            (56, "Ladoga Auto", "ladoga_auto", 0),
            (57, "Lateds AS", "lateds_as", 0),
            (58, "Latvijas Vagonu Rupnica", "latvijas_vagonu_rupnica", 0),
            (59, "Libellula", "libellula", 0),
            (60, "Lindakainen", "lindakainen", 0),
            (61, "Lisette Logistics", "lisette_logistics", 0),
            (62, "LKW", "lkw", 0),
            (63, "Maatila Egres", "maatila_egres", 0),
            (64, "Marina", "marina", 0),
            (65, "MarmoSpA", "marmospa", 0),
            (66, "MS Stein", "ms_stein", 0),
            (67, "MVM Carriere", "mvm_carriere", 0),
            (68, "NBFC", "nbfc", 0),
            (69, "Nordic Cargo Handling", "nordic_cargo_handling", 0),
            (70, "Nordic Crown", "nordic_crown", 0),
            (71, "Nordic Stenbrott", "nordic_stenbrott", 0),
            (72, "Norrfood", "norrfood", 0),
            (73, "Norrsken", "norrsken", 0),
            (74, "Nos Pâturages", "nos_paturages", 0),
            (75, "Noskonitta", "noskonitta", 0),
            (76, "NS Chemicals", "ns_chemicals", 0),
            (77, "NS Oil", "ns_oil", 0),
            (78, "Nucleon", "nucleon", 0),
            (79, "Onnelik Talu", "onnelik_talu", 0),
            (80, "PIAC", "piac", 0),
            (81, "PK Medved", "pk_medved", 0),
            (82, "Polar Fish", "polar_fish", 0),
            (83, "Polaris Lines", "polaris_lines", 0),
            (84, "Port de Conteneur", "port_de_conteneur", 0),
            (85, "Posped", "posped", 0),
            (86, "PP Chimica Italia", "pp_chimica_italia", 0),
            (87, "QuadrelliSpA", "quadrellispa", 0),
            (88, "Radus", "radus", 0),
            (89, "Renar Logistik", "renar_logistik", 0),
            (90, "Renat", "renat", 0),
            (91, "Rosmark", "rosmark", 0),
            (92, "S.A.L. S.R.L.", "sal_srl", 0),
            (93, "Sag & Tre", "sag_and_tre", 0),
            (94, "Sanbuilders", "sanbuilders", 0),
            (95, "Scania", "scania", 0),
            (96, "Scout", "scout", 0),
            (97, "SellPlan", "sellplan", 0),
            (98, "Severoatom", "severoatom", 0),
            (99, "Sininen Aurinko Logistiikka", "sininen_aurinko_logistiikka", 0),
            (100, "Spinelli", "spinelli", 0),
            (101, "Stein Bruch", "stein_bruch", 0),
            (102, "Stokes", "stokes", 0),
            (103, "Subse", "subse", 0),
            (104, "Suprema", "suprema", 0),
            (105, "TE Logistica", "te_logistica", 0),
            (106, "Terminal Container", "terminal_container", 0),
            (107, "Tesoro Gustoso", "tesoro_gustoso", 0),
            (108, "Tradeaux", "tradeaux", 0),
            (109, "Trameri", "trameri", 0),
            (110, "Transinet", "transinet", 0),
            (111, "Trasporti Mediterraneo", "trasporti_mediterraneo", 0),
            (112, "TREE-ET", "tree-et", 0),
            (113, "Ukko Voima", "ukko_voima", 0),
            (114, "Vanha Kivi", "vanha_kivi", 0),
            (115, "Viljo Paperitehdas Oy", "viljo_paperitehdas_oy", 0),
            (116, "Vilniaus Popieriaus Fabrikas", "vilniaus_popieriaus_fabrikas", 0),
            (117, "Vitas Power", "vitas_power", 0),
            (118, "Voitureux", "voitureux", 0),
            (119, "Volvo", "volvo", 0),
            (120, "VPC", "vpc", 0),
            (121, "VRM Oil", "vrm_oil", 0),
            (122, "WGCC", "wgcc", 0),
            (123, "Wilnet Transport", "wilnet_transport", 0),
            (124, "Zelenye Polja", "zelenye_polja", 0),
            (125, "42 Print", "42_print", 1),
            (126, "ABQ Cargo Center", "abq_cargo_center", 1),
            (127, "Avalanche Steel", "avalanche_steel", 1),
            (128, "Bitumen", "bitumen", 1),
            (129, "Bushnell Farms", "bushnell_farms", 1),
            (130, "Charged", "charged", 1),
            (131, "Chemso", "chemso", 1),
            (132, "Coastline Mining", "coastline_mining", 1),
            (133, "Darchelle Uzau", "darchelle_uzau", 1),
            (134, "Darwing", "darwing", 1),
            (135, "Deepgrove", "deepgrove", 1),
            (136, "Drake Car Dealer", "drake_car_dealer", 1),
            (137, "Eddy\"s", "eddy-s", 1),
            (138, "Fish Tail Foods", "fish_tail_foods", 1),
            (139, "Gallon Oil", "gallon_oil", 1),
            (140, "Global Mills", "global_mills", 1),
            (141, "Haddock Shipyard", "haddock_shipyard", 1),
            (142, "Heartwood Furniture", "heartwood_furniture", 1),
            (143, "HMS Machinery", "hms_machinery", 1),
            (144, "Home Store", "home_store", 1),
            (145, "Oakland Shippers", "oakland_shippers", 1),
            (146, "Olthon Homes", "olthon_homes", 1),
            (147, "Page & Price Paper", "page_and_price_paper", 1),
            (148, "Phoenix Freight", "phoenix_freight", 1),
            (149, "Plaster & Sons", "plaster_and_sons", 1),
            (150, "Port of San Francisco", "port_of_san_francisco", 1),
            (151, "Port of Seattle", "port_of_seattle", 1),
            (152, "Port of Tacoma", "port_of_tacoma", 1),
            (153, "Portland Cargo Central", "portland_cargo_central", 1),
            (154, "Rail Export", "rail_export", 1),
            (155, "Sea Horizon", "sea_horizon", 1),
            (156, "Sell Goods", "sell_goods", 1),
            (157, "Steeler", "steeler", 1),
            (158, "Sunshine Crops", "sunshine_crops", 1),
            (159, "Tidbit", "tidbit", 1),
            (160, "Voltison Motors", "voltison_motors", 1),
            (161, "Wallbert", "wallbert", 1)'));
            $result2 = $f3->get('result2');
            if($result2)
            {
                $f3->set('result3',$db->exec('CREATE TABLE `dlcs` (
                    `id` int(11) NOT NULL AUTO_INCREMENT,
                    `name` varchar(50) NOT NULL,
                    `short_name` varchar(50) NOT NULL,
                    PRIMARY KEY(`id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'));
                $f3->set('result3',$db->exec('INSERT INTO `dlcs` (`id`, `name`, `short_name`) VALUES
                (1, "ETS2 - Going East!", "dlc_goingeast"),
                (2, "ETS2 - Scandinavia", "dlc_scandinavia"),
                (3, "ETS2 - Vive La France!", "dlc_vivelafrance"),
                (4, "ETS2 - Italia", "dlc_italia"),
                (5, "ETS2 - Beyond the Baltic Sea", "dlc_beyondthebaltic"),
                (6, "ETS2 - Road to the Black Sea", "dlc_roadtotheblack"),
                (7, "ATS - New Mexico", "dlc_newmexico"),
                (8, "ATS - Oregon", "dlc_oregon"),
                (9, "ATS - Washington", "dlc_washington"),
                (10, "ATS - Utah", "dlc_utah")'));
                $result3 = $f3->get('result3');
                if($result3)
                {
                    $f3->set('result4',$db->exec('CREATE TABLE `load_tonnage` (
                        `id` int(11) NOT NULL AUTO_INCREMENT,
                        `short_name` varchar(50) NOT NULL,
                        `game` tinyint(1) NOT NULL,
                        `tonnage` varchar(50) NOT NULL,
                        PRIMARY KEY(`id`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                    $f3->set('result4',$db->exec('INSERT INTO `load_tonnage` (`id`, `short_name`, `game`, `tonnage`) VALUES
                    (1, "acetylene", 0, "12"),
                    (2, "acid", 0, "20"),
                    (3, "aircraft_tyres", 0, "18"),
                    (4, "air_conditioners", 0, "11"),
                    (5, "air_mails", 0, "10"),
                    (6, "almond", 0, "17"),
                    (7, "ammunition", 0, "18"),
                    (8, "apples", 0, "15-20"),
                    (9, "arsenic", 0, "23"),
                    (10, "asphalt_miller", 0, "44"),
                    (11, "atlantic_cod_fillet", 0, "16"),
                    (12, "backhoe_loader", 0, "8"),
                    (13, "barley", 0, "17"),
                    (14, "basil", 0, "19-24"),
                    (15, "beans", 0, "12"),
                    (16, "beef", 0, "17-21"),
                    (17, "beverages", 0, "10-24"),
                    (18, "bigbags_of_seeds", 0, "19"),
                    (19, "boiler_part", 0, "45"),
                    (20, "boric_acid", 0, "16"),
                    (21, "bottled_water", 0, "19-24"),
                    (22, "braco_vans", 0, "6"),
                    (23, "brake_fluid", 0, "6-8"),
                    (24, "brake_pads", 0, "?"),
                    (25, "bricks", 0, "?"),
                    (26, "canned_beans", 0, "16"),
                    (27, "canned_iced_coffee", 0, "21"),
                    (28, "canned_pork", 0, "17-21"),
                    (29, "canned_sardines", 0, "18"),
                    (30, "canned_tuna", 0, "17-18"),
                    (31, "carbonated_black_powder", 0, "9-19"),
                    (32, "carbonated_water", 0, "19-24"),
                    (33, "carrots", 0, "9-17"),
                    (34, "cars", 0, "7-9"),
                    (35, "cauliflower", 0, "9"),
                    (36, "caviar", 0, "14"),
                    (37, "cement", 0, "22"),
                    (38, "cheese", 0, "15-18"),
                    (39, "chemicals", 0, "19-20"),
                    (40, "chemical_sorbent", 0, "3-11"),
                    (41, "chewing_gums", 0, "22-23"),
                    (42, "chicken_meat", 0, "17"),
                    (43, "chimney_systems", 0, "18"),
                    (44, "chocolate", 0, "19-24"),
                    (45, "chlorine", 0, "17"),
                    (46, "clothes", 0, "15-24"),
                    (47, "coal", 0, "14"),
                    (48, "coconut_milk", 0, "19-24"),
                    (49, "coconut_oil", 0, "19-24"),
                    (50, "computer_processors", 0, "3"),
                    (51, "concentrate_juices", 0, "19-24"),
                    (52, "concrete_beams", 0, "17-19"),
                    (53, "concrete_beams_hcp", 0, "51"),
                    (54, "concrete_centering", 0, "18"),
                    (55, "concrete_stairs", 0, "19"),
                    (56, "construction_staircase", 0, "50"),
                    (57, "containerized_trees", 0, "4"),
                    (58, "contaminated_material", 0, "16"),
                    (59, "copper_roof_gutters", 0, "8"),
                    (60, "corks", 0, "5"),
                    (61, "cottage_cheese", 0, "17-18"),
                    (62, "cut_flowers", 0, "1"),
                    (63, "cyanide", 0, "18"),
                    (64, "diesel", 0, "23-25"),
                    (65, "diesel_generators", 0, "6"),
                    (66, "disinfectant", 0, "16"),
                    (67, "dozer_crawl", 0, "39"),
                    (68, "driller", 0, "8"),
                    (69, "dryers", 0, "13"),
                    (70, "dry_milk", 0, "18"),
                    (71, "dynamite", 0, "17"),
                    (72, "electronics", 0, "8"),
                    (73, "empty_barrels", 0, "9"),
                    (74, "empty_pallets", 0, "21-22"),
                    (75, "empty_wine_barrels", 0, "7"),
                    (76, "empty_wine_bottles", 0, "13"),
                    (77, "excavated_soil", 0, "23"),
                    (78, "excavator", 0, "22-24"),
                    (79, "excavator_bucket", 0, "25"),
                    (80, "exhaust_systems", 0, "9-18"),
                    (81, "explosives", 0, "12"),
                    (82, "fertilizer", 0, "20"),
                    (83, "fireworks", 0, "9"),
                    (84, "fish_fingers", 0, "17"),
                    (85, "floor_panels", 0, "23"),
                    (86, "flour", 0, "20"),
                    (87, "fluorine", 0, "?"),
                    (88, "forklifts", 0, "11"),
                    (89, "fresh_fish", 0, "18"),
                    (90, "fresh_herbs", 0, "5"),
                    (91, "frozen_hake", 0, "17"),
                    (92, "frozen_octopi", 0, "23"),
                    (93, "fuel_oil", 0, "19"),
                    (94, "fuel_tanker", 0, "12"),
                    (95, "fuel_tanks", 0, "10"),
                    (96, "furniture", 0, "16"),
                    (97, "garlic", 0, "12"),
                    (98, "gas_pipeline_parts", 0, "22-24"),
                    (99, "giant_silo", 0, "40"),
                    (100, "glass_panels", 0, "21"),
                    (101, "gnocchi", 0, "18"),
                    (102, "goat_cheese", 0, "15"),
                    (103, "granite_cubes", 0, "23"),
                    (104, "grapes", 0, "14"),
                    (105, "graphite_grease", 0, "16"),
                    (106, "grass_rolls", 0, "15"),
                    (107, "gravel", 0, "16"),
                    (108, "guard_rails", 0, "?"),
                    (109, "gummy_bears", 0, "?"),
                    (110, "harvesting_bins", 0, "2"),
                    (111, "haul_truck_chassis", 0, "55"),
                    (112, "heat_exchanger", 0, "70"),
                    (113, "heavy_metals", 0, "24"),
                    (114, "helicopter_ring", 0, "3"),
                    (115, "hightech_device", 0, "45"),
                    (116, "high_pressure_slide_valves", 0, "19"),
                    (117, "high_voltage_cables", 0, "9-21"),
                    (118, "honey", 0, "20"),
                    (119, "hospital_waste", 0, "17"),
                    (120, "hot_chemicals", 0, "20"),
                    (121, "huge_tyres", 0, "25"),
                    (122, "hydrochloric_acid", 0, "22"),
                    (123, "hydrogen", 0, "4"),
                    (124, "ibc_containers", 0, "11"),
                    (125, "ice_cream", 0, "14"),
                    (126, "industrial_condensator", 0, "60"),
                    (127, "industrial_cable_reel", 0, "34"),
                    (128, "iron_pipes", 0, "18-24"),
                    (129, "kerosene", 0, "18"),
                    (130, "ketchup", 0, "15"),
                    (131, "lamb_stomachs", 0, "13"),
                    (132, "large_tubes", 0, "22"),
                    (133, "lavender", 0, "8"),
                    (134, "lead", 0, "23"),
                    (135, "lemonade", 0, "23-24"),
                    (136, "liver_paste", 0, "17"),
                    (137, "live_cattle", 0, "14"),
                    (138, "loaders", 0, "22-23"),
                    (139, "locomotive", 0, "61"),
                    (140, "logs", 0, "22"),
                    (141, "low_bed_semitrailers", 0, "11"),
                    (142, "lpg", 0, "21"),
                    (143, "lumber", 0, "21"),
                    (144, "magnesium", 0, "17-19"),
                    (145, "maple_syrup", 0, "8-17"),
                    (146, "marble_blocks", 0, "22"),
                    (147, "marble_slab", 0, "11-23"),
                    (148, "mason_jars", 0, "7"),
                    (149, "massive_tech_part", 0, "44"),
                    (150, "medical_equipment", 0, "5"),
                    (151, "medical_vaccines", 0, "5"),
                    (152, "mercuric_acid", 0, "14-15"),
                    (153, "metal_beams", 0, "19-21"),
                    (154, "metal_cans", 0, "4"),
                    (155, "metal_centering", 0, "28"),
                    (156, "metal_coil", 0, "12-24"),
                    (157, "milk", 0, "14-15"),
                    (158, "mobile_crane", 0, "36"),
                    (159, "motorcycles", 0, "7-15"),
                    (160, "motorcycle_tyres", 0, "22"),
                    (161, "motor_oil", 0, "15-18"),
                    (162, "mozzarela", 0, "20"),
                    (163, "natural_rubber", 0, "21"),
                    (164, "neon", 0, "9-12"),
                    (165, "nitrocellulose", 0, "13-14"),
                    (166, "nitrogen", 0, "7-9"),
                    (167, "nonalcoholic_beer", 0, "22"),
                    (168, "nuts", 0, "18"),
                    (169, "nylon_cord", 0, "10-24"),
                    (170, "office_paper", 0, "18"),
                    (171, "oil", 0, "9"),
                    (172, "oil_filters", 0, "9-12"),
                    (173, "olives", 0, "6-27"),
                    (174, "olive_oil", 0, "8"),
                    (175, "onions", 0, "17"),
                    (176, "oranges", 0, "20"),
                    (177, "ore", 0, "18"),
                    (178, "outdoor_floor_tiles", 0, "20"),
                    (179, "packaged_food", 0, "17"),
                    (180, "packed_glass", 0, "22"),
                    (181, "pasta", 0, "20"),
                    (182, "peanut_butter", 0, "19"),
                    (183, "pears", 0, "15"),
                    (184, "peas", 0, "18"),
                    (185, "perfomance_forks", 0, "16"),
                    (186, "pesticides", 0, "14-15"),
                    (187, "pesto", 0, "15"),
                    (188, "petrol", 0, "21"),
                    (189, "pet_food", 0, "9-20"),
                    (190, "plastic_film_rolls", 0, "12-18"),
                    (191, "plastic_granules", 0, "19"),
                    (192, "plumbing_supplies", 0, "18"),
                    (193, "plums", 0, "16"),
                    (194, "polystyrene_boxes", 0, "3"),
                    (195, "pork", 0, "18"),
                    (196, "post_packages", 0, "11"),
                    (197, "potassium", 0, "17"),
                    (198, "potassium_hydroxide", 0, "20"),
                    (199, "potatoes", 0, "21-22"),
                    (200, "potted_flowers", 0, "3"),
                    (201, "precast_stairs", 0, "21-22"),
                    (202, "pressure_tank", 0, "12-22"),
                    (203, "prosciutto", 0, "16"),
                    (204, "protective_clothing", 0, "20-30"),
                    (205, "pumps", 0, "14"),
                    (206, "radiators", 0, "4-9"),
                    (207, "reflective_posts", 0, "6-12"),
                    (208, "reinforcing_bars", 0, "21-24"),
                    (209, "reservoir_tank", 0, "11"),
                    (210, "rice", 0, "17-22"),
                    (211, "roller", 0, "8"),
                    (212, "roofing_felt", 0, "7-19"),
                    (213, "rooflights", 0, "2-5"),
                    (214, "roof_tiles", 0, "20-30"),
                    (215, "rye", 0, "17"),
                    (216, "salmon_fillet", 0, "14"),
                    (217, "salt_and_spices", 0, "12-16"),
                    (218, "sand", 0, "16"),
                    (219, "sandwich_panels", 0, "12"),
                    (220, "sausages", 0, "17"),
                    (221, "sawdust_panels", 0, "21"),
                    (222, "scaffoldings", 0, "22"),
                    (223, "scania_trucks", 0, "14"),
                    (224, "scooters", 0, "9-10"),
                    (225, "scrap_metals", 0, "15"),
                    (226, "sealed_bearings", 0, "24"),
                    (227, "service_boat", 0, "25"),
                    (228, "sheep_wool", 0, "6-13"),
                    (229, "shock_absorbers", 0, "11-16"),
                    (230, "silica", 0, "18"),
                    (231, "smoked_eel", 0, "11"),
                    (232, "smoked_sprats", 0, "17"),
                    (233, "sodium", 0, "16-19"),
                    (234, "sodium_hydroxide", 0, "18-20"),
                    (235, "sodium_hypochloride", 0, "19"),
                    (236, "soy_milk", 0, "21"),
                    (237, "spherical_valves", 0, "22"),
                    (238, "square_tubings", 0, "12-25"),
                    (239, "steel_cord", 0, "14"),
                    (240, "stones", 0, "20"),
                    (241, "stone_dust", 0, "17"),
                    (242, "stone_wool", 0, "2-5"),
                    (243, "straw_bales", 0, "15"),
                    (244, "sugar", 0, "22"),
                    (245, "sulfuric_acid", 0, "14-23"),
                    (246, "tableware", 0, "15-16"),
                    (247, "tomatoes", 0, "18"),
                    (248, "toys", 0, "9"),
                    (249, "tracks", 0, "11"),
                    (250, "tractors", 0, "11-13"),
                    (251, "tractor_rs666", 0, "13"),
                    (252, "train_axles", 0, "20"),
                    (253, "train_undercarriage", 0, "20"),
                    (254, "transformer", 0, "47"),
                    (255, "transmissions", 0, "12-14"),
                    (256, "truck_batteries", 0, "14-18"),
                    (257, "truck_rims", 0, "9-12"),
                    (258, "truck_tyres", 0, "13"),
                    (259, "tyres", 0, "16"),
                    (260, "used_car_batteries", 0, "16-17"),
                    (261, "used_packagings", 0, "20-30"),
                    (262, "used_plastics", 0, "7-9"),
                    (263, "ventilation_shaft", 0, "4"),
                    (264, "vinegar", 0, "9-15"),
                    (265, "volvo_truck", 0, "14"),
                    (266, "wall_panels", 0, "22"),
                    (267, "watermelons", 0, "20"),
                    (268, "wheat", 0, "17"),
                    (269, "wheel_loader", 0, "8-15"),
                    (270, "white_phosphorus", 0, "10-11"),
                    (271, "wind_turbine_nacelle", 0, "21"),
                    (272, "wind_turbine_tower", 0, "19"),
                    (273, "wooden_beams", 0, "21-22"),
                    (274, "wood_bark", 0, "15"),
                    (275, "work_clothes", 0, "15-16"),
                    (276, "yacht", 0, "6"),
                    (277, "yacht_queen_v39", 0, "9"),
                    (278, "yoghurt", 0, "17"),
                    (279, "young_seedlings", 0, "3"),
                    (280, "backflow_preventers", 0, "24"),
                    (281, "canned_beef", 0, "15-22"),
                    (282, "electrical_wiring", 0, "12-15"),
                    (283, "air_conditining_complex", 1, "?"),
                    (284, "aircraft_engine", 1, "?"),
                    (285, "all_terrain_crane", 1, "?"),
                    (286, "aromatics", 1, "12"),
                    (287, "backhoe_loader", 1, "?"),
                    (288, "beverages", 1, "19"),
                    (289, "boat", 1, "?"),
                    (290, "bulldozer", 1, "20"),
                    (291, "butter", 1, "17"),
                    (292, "cable_reel", 1, "29"),
                    (293, "cables", 1, "20"),
                    (294, "car_parts", 1, "9-10"),
                    (295, "cars", 1, "7-10"),
                    (296, "cement", 1, "17"),
                    (297, "cheese", 1, "13"),
                    (298, "clothes", 1, "8-12"),
                    (299, "computers", 1, "9"),
                    (300, "concrete_tubes", 1, "15"),
                    (301, "construction_houses", 1, "7"),
                    (302, "crawler_tractor", 1, "?"),
                    (303, "curtains", 1, "11-16"),
                    (304, "diesel", 1, "16-19"),
                    (305, "dry_fruits", 1, "12"),
                    (306, "dry_milk", 1, "11"),
                    (307, "dynamite", 1, "16"),
                    (308, "electronic_components", 1, "6"),
                    (309, "empty_bottles", 1, "14-18"),
                    (310, "empty_pallets", 1, "12"),
                    (311, "ethane", 1, "17"),
                    (312, "excavated_soil", 1, "17-24"),
                    (313, "excavator", 1, "19"),
                    (314, "fertilizer", 1, "14"),
                    (315, "fireworks", 1, "4-6"),
                    (316, "flour", 1, "14-20"),
                    (317, "forklifts", 1, "7"),
                    (318, "forwarder", 1, "?"),
                    (319, "frozen_food", 1, "19"),
                    (320, "frozen_fruits", 1, "16"),
                    (321, "frozen_vegetables", 1, "15"),
                    (322, "fruits", 1, "12-16"),
                    (323, "furniture", 1, "8-15"),
                    (324, "giant_silo", 1, "?"),
                    (325, "grain", 1, "13"),
                    (326, "gravel", 1, "17"),
                    (327, "gypsum", 1, "15-20"),
                    (328, "haul_truck_chassis", 1, "?"),
                    (329, "haul_truck_hull", 1, "?"),
                    (330, "hay", 1, "9"),
                    (331, "home_accesories", 1, "11-19"),
                    (332, "household_appliances", 1, "6-11"),
                    (333, "huge_construction", 1, "?"),
                    (334, "huge_tyres", 1, "?"),
                    (335, "ice_cream", 1, "19"),
                    (336, "iron_pipes", 1, "18"),
                    (337, "kenworth_trucks", 1, "?"),
                    (338, "knuckleboom_loader", 1, "?"),
                    (339, "large_reservoir_tank", 1, "?"),
                    (340, "large_tubes", 1, "?"),
                    (341, "lift_truck", 1, "?"),
                    (342, "lift_truck_chassis", 1, "?"),
                    (343, "limestone", 1, "17"),
                    (344, "log_harvester", 1, "?"),
                    (345, "log_loader", 1, "?"),
                    (346, "log_stacker", 1, "?"),
                    (347, "logs", 1, "?"),
                    (348, "lumber", 1, "20"),
                    (349, "lye", 1, "14"),
                    (350, "machine_parts", 1, "8-9"),
                    (351, "massive_tech_part", 1, "?"),
                    (352, "meat", 1, "14-17"),
                    (353, "mercuric_chloride", 1, "18"),
                    (354, "metal_coil", 1, "?"),
                    (355, "milk", 1, "18"),
                    (356, "milling_machine", 1, "43"),
                    (357, "mobile_barrier", 1, "0"),
                    (358, "mooring_buoy", 1, "?"),
                    (359, "mortar", 1, "15"),
                    (360, "mulcher", 1, "?"),
                    (361, "nitrocellulose", 1, "9"),
                    (362, "nuts", 1, "11"),
                    (363, "office_supplies", 1, "9-16"),
                    (364, "packaged_food", 1, "11-17"),
                    (365, "paint", 1, "?"),
                    (366, "pesticides", 1, "17"),
                    (367, "petrol", 1, "18"),
                    (368, "plows", 1, "2"),
                    (369, "potassium", 1, "19"),
                    (370, "power_generator", 1, "?"),
                    (371, "pressure_tank", 1, "19"),
                    (372, "propane", 1, "18"),
                    (373, "raw_milk", 1, "14"),
                    (374, "reservoir_tank", 1, "?"),
                    (375, "rice", 1, "13"),
                    (376, "roadroller", 1, "9"),
                    (377, "sand", 1, "18"),
                    (378, "sawdust_panels", 1, "14-17"),
                    (379, "scrap_metal", 1, "?"),
                    (380, "scraper", 1, "?"),
                    (381, "scrapped_cars", 1, "?"),
                    (382, "service_boat", 1, "?"),
                    (383, "silica", 1, "13-19"),
                    (384, "solvents", 1, "13"),
                    (385, "square_tubing", 1, "?"),
                    (386, "stones", 1, "17-24"),
                    (387, "stumper", 1, "?"),
                    (388, "sugar", 1, "12"),
                    (389, "sulfuric_acid", 1, "19"),
                    (390, "tableware", 1, "10"),
                    (391, "toys", 1, "8-13"),
                    (392, "tractors", 1, "13-14"),
                    (393, "transformer_ats", 1, "55"),
                    (394, "transport_helicopter", 1, "?"),
                    (395, "tub_grinder", 1, "?"),
                    (396, "turnkey_house_construction", 1, "?"),
                    (397, "tvs", 1, "8"),
                    (398, "tyres", 1, "14-19"),
                    (399, "used_packagings", 1, "?"),
                    (400, "vegetables", 1, "10-19"),
                    (401, "ventilation_shaft", 1, "5"),
                    (402, "wheel_loader", 1, "7-15"),
                    (403, "wood_shavings", 1, "16-17"),
                    (404, "yoghurt", 1, "17")'));
                    $result4 = $f3->get('result4');
                    if($result4)
                    {
                        $f3->set('result5',$db->exec('CREATE TABLE `notifications` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `user_id` int(11) NOT NULL,
                            `type` varchar(50) NOT NULL,
                            `information` varchar(500) NOT NULL,
                            `is_read` tinyint(1) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('CREATE TABLE `pass_url` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `id_user` int(11) NOT NULL,
                            `hash` varchar(200) NOT NULL,
                            `expire` datetime NOT NULL,
                            `used` tinyint(1) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('CREATE TABLE `recrutation` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `nickname` varchar(50) NOT NULL,
                            `steam_id` bigint(20) NOT NULL,
                            `steam_link` varchar(150) NOT NULL,
                            `on_tmp` tinyint(1) NOT NULL,
                            `ats` tinyint(1) NOT NULL,
                            `dlcs` varchar(50) NOT NULL,
                            `age` int(11) NOT NULL,
                            `email` varchar(50) NOT NULL,
                            `why_u` varchar(150) NOT NULL,
                            `why_us` varchar(150) NOT NULL,
                            `status` int(11) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('CREATE TABLE `roles` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `name` varchar(50) NOT NULL,
                            `short_name` varchar(50) NOT NULL,
                            `admin` tinyint(1) NOT NULL,
                            `edit_user` tinyint(1) NOT NULL,
                            `color` varchar(50) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('INSERT INTO `roles` (`id`, `name`, `short_name`, `admin`, `edit_user`, `color`) VALUES
                        (1, "Admin", "admin", 1, 1, "text-danger"),
                        (2, "User", "user", 0, 0, "text-default")'));
                        $f3->set('result5',$db->exec('CREATE TABLE `settings` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `name` varchar(100) NOT NULL,
                            `value` varchar(100) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('CREATE TABLE `trips` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `city_from` varchar(40) NOT NULL,
                            `comp_from` varchar(50) NOT NULL,
                            `city_to` varchar(40) NOT NULL,
                            `comp_to` varchar(50) NOT NULL,
                            `date_beg` datetime NOT NULL,
                            `date_end` datetime NOT NULL,
                            `load_type` varchar(40) NOT NULL,
                            `tonnage` int(11) NOT NULL,
                            `distance` int(11) NOT NULL,
                            `fuel_used` float(6,2) NOT NULL,
                            `damage` int(11) NOT NULL,
                            `money` int(11) NOT NULL,
                            `image_end` varchar(150) NOT NULL,
                            `status` int(11) NOT NULL,
                            `id_user` int(11) NOT NULL,
                            `id_admin` int(11) NOT NULL,
                            `participate_convoy` int(11) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('CREATE TABLE `convoys` ( 
                            `id` INT NOT NULL AUTO_INCREMENT, 
                            `c_start` VARCHAR(50) NOT NULL, 
                            `comp_start` VARCHAR(50) NOT NULL, 
                            `c_end` VARCHAR(50) NOT NULL, 
                            `comp_end` VARCHAR(50) NOT NULL, 
                            `name` VARCHAR(100) NOT NULL, 
                            `game` BOOLEAN NOT NULL, 
                            `date_beg_convoy` DATE NOT NULL, 
                            `time_beg_convoy` TIME NOT NULL, 
                            `time_groupup` TIME NOT NULL, 
                            `server_game` VARCHAR(50) NOT NULL, 
                            `server_voip` VARCHAR(100) NULL, 
                            `route` VARCHAR(100) NULL, 
                            `image_start` VARCHAR(100) NULL, 
                            `image_end` VARCHAR(100) NULL, 
                            `rules` VARCHAR(1000) NULL, 
                            `private` BOOLEAN NOT NULL, 
                            PRIMARY KEY (`id`)
                        ) ENGINE = InnoDB DEFAULT CHARSET=utf8;'));
                        $f3->set('result5',$db->exec('CREATE TABLE `trucks` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `name` varchar(50) NOT NULL,
                            `short_name` varchar(50) NOT NULL,
                            `game` tinyint(1) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $f3->set('result5',$db->exec('INSERT INTO `trucks` (`id`, `name`, `short_name`, `game`) VALUES
                        (1, "DAF XF105", "daf_xf", 0),
                        (2, "DAF XF Euro 6", "daf_xf_e6", 0),
                        (3, "Iveco Stralis", "iveco_stralis", 0),
                        (4, "Iveco Stralis Hi-Way", "iveco_hiway", 0),
                        (5, "MAN TGX", "man_tgx", 0),
                        (6, "MAN TGX Euro 6", "man_tgx_e6", 0),
                        (7, "Mercedes Actros", "merc_actros", 0),
                        (8, "Mercedes New Actros", "merc_newactros", 0),
                        (9, "Renault Magnum", "ren_magnum", 0),
                        (10, "Renault Premium", "ren_premium", 0),
                        (11, "Renault T", "ren_t", 0),
                        (12, "Scania Streamline", "scania_stream", 0),
                        (13, "Scania R (2009)", "scania_r2009", 0),
                        (14, "Scania S", "scania_s", 0),
                        (15, "Scania R", "scania_r", 0),
                        (16, "Volvo FH16 Classic", "volvo_fh16", 0),
                        (17, "Volvo FH", "volvo_fh", 0),
                        (18, "Kenworth W900", "kenworth_w900", 1),
                        (19, "Kenworth T680", "kenworth_t680", 1),
                        (20, "Peterbilt 389", "peterbilt_389", 1),
                        (21, "Peterbilt 579", "peterbilt_579", 1),
                        (22, "Volvo VNL", "volvo_vnl", 1),
                        (23, "International Lonestar", "inter_lone", 1)'));
                        $f3->set('result5',$db->exec('CREATE TABLE `users` (
                            `id` int(11) NOT NULL AUTO_INCREMENT,
                            `nickname` varchar(50) NOT NULL,
                            `email` varchar(50) NOT NULL,
                            `pass_hash` varchar(100) NOT NULL,
                            `img_profile` varchar(50) DEFAULT NULL,
                            `ats` tinyint(1) NOT NULL,
                            `tmpid` int(11) NOT NULL,
                            `truck_ets2` varchar(50) NOT NULL,
                            `truck_ats` varchar(50) NOT NULL,
                            `dlcs` varchar(200) NOT NULL,
                            `role_id` int(11) NOT NULL,
                            PRIMARY KEY(`id`)
                          ) ENGINE=InnoDB DEFAULT CHARSET=utf8'));
                        $result5 = $f3->get('result5');
                        if($result5 === 0)
                        {
                            $f3->set('set_globals',$db->exec('INSERT INTO `settings` (`id`, `name`, `value`) VALUES
                            (1, "vtc_name", ?),
                            (2, "vtc_logo", ?),
                            (3, "vtc_slogan", ?),
                            (4, "vtc_tmpid", ?),
                            (5, "unit_distance", "km"),
                            (6, "unit_fuel", "L"),
                            (7, "unit_tonnage", "t"),
                            (8, "unit_money", "euro"),
                            (9, "date_format", "d.m.Y"),
                            (10, "time_format", "H:i"),
                            (11, "recrutation", "1"),
                            (12, "email_address", ?),
                            (13, "email_pass", ?),
                            (14, "mail_server", ?),
                            (15, "method_connection", ?),
                            (16, "port_number_smtp", ?),
                            (17, "steam_api_key", ?)',array(
                                $vtc_name,
                                $vtc_logo,
                                $vtc_slogan,
                                $vtc_tmpid,
                                $smtp_email,
                                $smtp_pass,
                                $smtp_host,
                                $smtp_method,
                                $smtp_port,
                                $api_key
                            )));
                            $set_globals = $f3->get('set_globals');
                            $hash_pass=uniqid(NULL,TRUE);
                            $expiration_date = date('Y-m-d H:i',time()+28880);
                            $f3->set('result_ins',$db->exec('INSERT INTO pass_url VALUES(NULL,1,?,?,false)',array($hash_pass,$expiration_date)));
                            $result_ins = $f3->get('result_ins');
                            $f3->set('add_user',$db->exec('INSERT INTO `users` (`id`, `nickname`, `email`, `pass_hash`, `img_profile`, `ats`, `tmpid`, `truck_ets2`, `truck_ats`, `dlcs`, `role_id`) VALUES
                            (1,?,?, "", NULL, 0, 0, "", "", "", 1)',array($admin_nickname,$admin_email)));
                            $add_user = $f3->get('add_user');
                            if($set_globals && $add_user && $result_ins)
                            {
                                $hash_mail=uniqid(NULL,TRUE);
                                $smtp = new SMTP ($smtp_host,$smtp_port,$smtp_method,$smtp_email,$smtp_pass);
                                $smtp->set('From', '"'.$vtc_name.'" <'.$smtp_email.'>');
                                $smtp->set('To', '<'.$admin_email.'>');
                                $smtp->set('Subject', $f3->get('change_password'));  
                                $smtp->set('Errors-to', '<'.$smtp_email.'>');
                                $smtp->set('Content-Type', 'text/html; boundary="'.$hash_mail.'"');
                                $server_name = $_SERVER['HTTP_HOST'];
                                $html = $f3->get('new_password_firstpart').'<a href="'.$server_name.'/set_password/'.$hash_pass.'">'.$f3->get('click_resetpass').'</a>'.$f3->get('new_password_secondpart');
                                
                                $eol="\r\n";
                                $body .= $html.$eol.$eol;

                                $sent = $smtp->send($body, TRUE);


                                $mylog = $smtp->log();

                                if ($sent)
                                {
                                    $functions = fopen('./app/functions.php', "w") or die("Unable to open file!");
                                    $db_connect = "<?php\n";
                                    $db_connect .= "if(file_exists('./LOCK'))\n{";
                                    $db_connect .= '$f3->set("db",new DB\SQL('."\n";
                                    $db_connect .= '"mysql:host='.$db_host.';post=3306;dbname='.$db_name.'",'."\n";
                                    $db_connect .= '"'.$db_nickname.'",'."\n";
                                    $db_connect .= '"'.$db_pass.'"));'."\n";
                                    $db_connect .= "}\nelse\n{";
                                    $db_connect .= '$host = "'.$db_host.'";\n';
                                    $db_connect .= '$dbname = "'.$db_name.'";\n';
                                    $db_connect .= '$username = "'.$db_nickname.'";\n';
                                    $db_connect .= '$password = "'.$db_pass.'";\n';

                                    fwrite($functions,$db_connect);
                                    fclose($functions);
                                    $lock = fopen('./LOCK','w') or die("Couln't create a file!");
                                    fwrite($lock,'');
                                    fclose($lock);
                                    header('Location: ./installer/success');
                                    exit();
                                }
                                else
                                {
                                    exit($mylog);
                                }
                            }
                            else
                            {
                                $_SESSION['error'] = '3';
                                header('Location: ./installer');
                                exit();
                            }
                        }
                        else
                        {
                            $_SESSION['error'] = '2';
                            header('Location: ./installer');
                            exit();
                        }
                    }
                    else
                    {
                        $_SESSION['error'] = '2';
                        header('Location: ./installer');
                        exit();
                    }
                }
                else
                {
                    $_SESSION['error'] = '2';
                    header('Location: ./installer');
                    exit();
                }
            }
            else
            {
                $_SESSION['error'] = '2';
                header('Location: ./installer');
                exit();
            }
        }
        else
        {
            $_SESSION['error'] = '2';
            header('Location: ./installer');
            exit();
        }
    }
    else
    {
        $_SESSION['error'] = '1';
        header('Location: ./installer');
        exit();
    }
?>